# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8482c4caf2b8a5305df7c956766c1bd7509b3b043fdff504ce1a8b502dad3a56b1d72db491915dfc940979c63763220796ce020eafbf66636270408f4057fc5

test:
  secret_key_base: ab5b71d75258e801a6da976fd2f988399798154b9689d3f680c1433921d27f04d3d497438545032ea3886dc777b3254667e5cb5b078d65ba5f6c41effd931f34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
